package com.desco.admin.enums;

public enum AreaName {
  
    UTTARA, GULSHAN, BANANI, DHANMONDI,
    BASHUNDHARA, MIRPUR, BANASREE, BARIDHARA,

    BARGUNA, BARISHAL, BHOLA, JHALOKATI,
    PATUAKHALI, PIROJPUR,
    // Chattogram
    BANDARBAN, BRAHMANBARIA, CHANDPUR, CHATTOGRAM,
    CUMILLA, COXS_BAZAR, FENI, KHAGRACHHARI,
    LAKSHMIPUR, NOAKHALI, RANGAMATI,
    // Dhaka
    DHAKA, FARIDPUR, GAZIPUR, GOPALGANJ,
    KISHOREGANJ, MADARIPUR, MANIKGANJ, MUNSHIGANJ,
    NARAYANGANJ, NARSINGDI, RAJBARI, SHARIATPUR,
    TANGAIL,
    // Khulna
    BAGERHAT, CHUADANGA, JASHORE, JHENAIDAH,
    KHULNA, KUSHTIA, MAGURA, MEHERPUR,
    NARAIL, SATKHIRA,
    // Mymensingh
    JAMALPUR, MYMENSINGH, NETROKONA, SHERPUR,
    // Rajshahi
    BOGURA, CHAPAINAWABGANJ, JOYPURHAT, NAOGAON,
    NATORE, PABNA, RAJSHAHI, SIRAJGANJ,
    // Rangpur
    DINAJPUR, GAIBANDHA, KURIGRAM, LALMONIRHAT,
    NILPHAMARI, PANCHAGARH, RANGPUR, THAKURGAON,
    // Sylhet
    HABIGANJ, MOULVIBAZAR, SUNAMGANJ, SYLHET
}
